#!/usr/bin/env sh
# Entrypoint for the middleman container.
#
# middleman binds a LOOPBACK address by design (it validates that host is
# loopback and refuses 0.0.0.0). To make it reachable from outside the
# container we run it on 127.0.0.1:${MIDDLEMAN_INTERNAL_PORT} and bridge
# 0.0.0.0:${MIDDLEMAN_PORT} -> that loopback port with socat (the same pattern
# the project's dev compose uses).
#
# On first run we seed a minimal config under MIDDLEMAN_HOME. An existing
# config is left untouched (edit it and restart to customize: repos, providers,
# allowed_hosts, etc.).
set -eu

: "${MIDDLEMAN_HOME:=/data}"
: "${MIDDLEMAN_PORT:=8091}"            # external port (socat listener; published)
: "${MIDDLEMAN_INTERNAL_PORT:=8092}"  # loopback port middleman binds
CONFIG="${MIDDLEMAN_HOME}/config.toml"

mkdir -p "${MIDDLEMAN_HOME}"

if [ ! -f "${CONFIG}" ]; then
  echo "middleman: seeding default config at ${CONFIG} (loopback :${MIDDLEMAN_INTERNAL_PORT})" >&2
  {
    echo '# Generated by docker-entrypoint.sh on first run.'
    echo '# Edit this file and restart the container to customize.'
    echo 'sync_interval = "5m"'
    echo 'github_token_env = "MIDDLEMAN_GITHUB_TOKEN"'
    echo 'host = "127.0.0.1"'
    echo "port = ${MIDDLEMAN_INTERNAL_PORT}"
    echo "data_dir = \"${MIDDLEMAN_HOME}\""
    # Requests arrive via socat with the original Host header, so the Host must be
    # allow-listed. Always allow the in-container healthcheck (loopback at the
    # external port); append operator-supplied MIDDLEMAN_ALLOWED_HOSTS (comma-
    # separated) for Tailscale/reverse-proxy domain access.
    allowed="\"127.0.0.1:${MIDDLEMAN_PORT}\", \"localhost:${MIDDLEMAN_PORT}\""
    if [ -n "${MIDDLEMAN_ALLOWED_HOSTS:-}" ]; then
      extra="$(printf '%s' "${MIDDLEMAN_ALLOWED_HOSTS}" \
        | awk -v RS=, '{gsub(/^[ \t]+|[ \t]+$/,""); if($0!="") printf ", \""$0"\""}')"
      allowed="${allowed}${extra}"
    fi
    echo "allowed_hosts = [${allowed}]"
    # Only enable when actually behind a reverse proxy that sets X-Forwarded-Host:
    # with it on, middleman REQUIRES a forwarded-host header on every request
    # (direct access and the healthcheck would otherwise be rejected).
    case "${MIDDLEMAN_TRUST_REVERSE_PROXY:-}" in
      1|true|TRUE|yes) echo 'trust_reverse_proxy = true' ;;
    esac
  } > "${CONFIG}"
fi

# Honor a hand-edited config: read the port middleman will actually bind.
backend_port="$(middleman config read -config "${CONFIG}" port 2>/dev/null || true)"
case "${backend_port}" in
  ''|*[!0-9]*) backend_port="${MIDDLEMAN_INTERNAL_PORT}" ;;
esac

socat "TCP-LISTEN:${MIDDLEMAN_PORT},fork,bind=0.0.0.0,reuseaddr" "TCP:127.0.0.1:${backend_port}" &
socat_pid=$!

# MIDDLEMAN_HOME makes the default config path resolve to ${CONFIG}.
middleman serve "$@" &
mm_pid=$!

terminate() { kill -TERM "${mm_pid}" "${socat_pid}" 2>/dev/null || true; }
trap terminate INT TERM

wait "${mm_pid}"
status=$?
kill -TERM "${socat_pid}" 2>/dev/null || true
wait "${socat_pid}" 2>/dev/null || true
exit "${status}"
