#!/usr/bin/env sh
# Entrypoint for the middleman container.
#
# middleman binds a LOOPBACK address by design (it validates that host is
# loopback and refuses 0.0.0.0). To make it reachable from outside the
# container we run it on 127.0.0.1:${MIDDLEMAN_INTERNAL_PORT} and bridge
# 0.0.0.0:${MIDDLEMAN_PORT} -> that loopback port with socat (the same pattern
# the project's dev compose uses).
#
# On first run we seed a minimal config under MIDDLEMAN_HOME. An existing
# config is left untouched (edit it and restart to customize: repos, providers,
# allowed_hosts, etc.).
set -eu

: "${MIDDLEMAN_HOME:=/data}"
: "${MIDDLEMAN_PORT:=8091}"            # external port (socat listener; published)
: "${MIDDLEMAN_INTERNAL_PORT:=8092}"  # loopback port middleman binds
CONFIG="${MIDDLEMAN_HOME}/config.toml"

# Strip quotes/backslashes/newlines so a value cannot break the generated TOML.
toml_safe() { printf '%s' "$1" | tr -d '"\\\n\r'; }

mkdir -p "${MIDDLEMAN_HOME}"

if [ ! -f "${CONFIG}" ]; then
  echo "middleman: seeding default config at ${CONFIG} (loopback :${MIDDLEMAN_INTERNAL_PORT})" >&2
  {
    echo '# Generated by docker-entrypoint.sh on first run.'
    echo '# Edit this file and restart the container to customize.'
    echo '# Keep host = "127.0.0.1": the socat bridge dials 127.0.0.1, so another'
    echo '# loopback form (e.g. [::1]) would start but be unreachable.'
    echo 'sync_interval = "5m"'
    echo 'github_token_env = "MIDDLEMAN_GITHUB_TOKEN"'
    echo 'host = "127.0.0.1"'
    echo "port = ${MIDDLEMAN_INTERNAL_PORT}"
    echo "data_dir = \"${MIDDLEMAN_HOME}\""
    # Requests arrive via socat with the original Host header, so the Host must be
    # allow-listed. Always allow the in-container healthcheck (loopback at the
    # external port); append operator-supplied MIDDLEMAN_ALLOWED_HOSTS (comma-
    # separated) for Tailscale/reverse-proxy domain access.
    allowed="\"127.0.0.1:${MIDDLEMAN_PORT}\", \"localhost:${MIDDLEMAN_PORT}\""
    if [ -n "${MIDDLEMAN_ALLOWED_HOSTS:-}" ]; then
      # Strip quotes/backslashes/newlines so a stray value cannot break the
      # generated TOML. Values must be bare host[:port] tokens.
      extra="$(printf '%s' "${MIDDLEMAN_ALLOWED_HOSTS}" \
        | tr -d '"\\\n\r' \
        | awk -v RS=, '{gsub(/^[ \t]+|[ \t]+$/,""); if($0!="") printf ", \""$0"\""}')"
      allowed="${allowed}${extra}"
    fi
    echo "allowed_hosts = [${allowed}]"
    # Only enable when actually behind a reverse proxy that sets X-Forwarded-Host:
    # with it on, middleman REQUIRES a forwarded-host header on every request
    # (direct access and the healthcheck would otherwise be rejected).
    case "${MIDDLEMAN_TRUST_REVERSE_PROXY:-}" in
      1|true|TRUE|yes) echo 'trust_reverse_proxy = true' ;;
    esac
    # Front door -> roborev proxy target (table must follow the top-level keys).
    if [ -n "${MIDDLEMAN_ROBOREV_ENDPOINT:-}" ]; then
      echo ''
      echo '[roborev]'
      echo "endpoint = \"$(toml_safe "${MIDDLEMAN_ROBOREV_ENDPOINT}")\""
    fi
  } > "${CONFIG}"
fi

# Front door -> kata proxy: middleman discovers daemons from $KATA_HOME/config.toml.
# Seed a catalog pointing at the in-network kata when MIDDLEMAN_KATA_URL is set.
if [ -n "${MIDDLEMAN_KATA_URL:-}" ]; then
  : "${KATA_HOME:=${MIDDLEMAN_HOME}/kata}"
  export KATA_HOME
  mkdir -p "${KATA_HOME}"
  [ -n "${KATA_AUTH_TOKEN:-}" ] || echo "middleman: warning: MIDDLEMAN_KATA_URL set but KATA_AUTH_TOKEN is empty; kata proxy will fail auth" >&2
  KATA_CATALOG="${KATA_HOME}/config.toml"
  if [ ! -f "${KATA_CATALOG}" ]; then
    echo "middleman: seeding kata catalog at ${KATA_CATALOG} -> ${MIDDLEMAN_KATA_URL}" >&2
    {
      echo 'active_daemon = "kenn-stack"'
      echo '[[daemon]]'
      echo 'name = "kenn-stack"'
      echo "url = \"$(toml_safe "${MIDDLEMAN_KATA_URL}")\""
      echo 'token_env = "KATA_AUTH_TOKEN"'
      echo 'allow_insecure = true'
    } > "${KATA_CATALOG}"
  fi
fi

# Seed-only mode: write the config and exit (used by tests to validate the
# generated config without starting the server). No middleman binary required.
if [ "${MIDDLEMAN_SEED_ONLY:-}" = "1" ]; then
  exit 0
fi

# Honor a hand-edited config: read the port middleman will actually bind.
backend_port="$(middleman config read -config "${CONFIG}" port 2>/dev/null || true)"
case "${backend_port}" in
  ''|*[!0-9]*) backend_port="${MIDDLEMAN_INTERNAL_PORT}" ;;
esac

socat "TCP-LISTEN:${MIDDLEMAN_PORT},fork,bind=0.0.0.0,reuseaddr" "TCP:127.0.0.1:${backend_port}" &
socat_pid=$!

# MIDDLEMAN_HOME makes the default config path resolve to ${CONFIG}.
middleman serve "$@" &
mm_pid=$!

terminate() { kill -TERM "${mm_pid}" "${socat_pid}" 2>/dev/null || true; }
trap terminate INT TERM

# Disable errexit around wait so a non-zero middleman exit still runs cleanup.
set +e
wait "${mm_pid}"
status=$?
set -e
kill -TERM "${socat_pid}" 2>/dev/null || true
wait "${socat_pid}" 2>/dev/null || true
exit "${status}"
